-- MySQL Script generated by MySQL Workbench
-- 02/16/18 18:41:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema form_ipt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema form_ipt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `form_ipt` DEFAULT CHARACTER SET utf8 ;
USE `form_ipt` ;

-- -----------------------------------------------------
-- Table `form_ipt`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_ipt`.`municipio` (
  `cod_ibge` INT(7) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `nome_municipio` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cod_ibge`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `form_ipt`.`form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `form_ipt`.`form` (
  `cod_ibge` INT(7) NOT NULL,
  `municipio_contatado` VARCHAR(50) NULL DEFAULT NULL,
  `nome_prefeito` VARCHAR(250) NULL DEFAULT NULL,
  `solicitante` VARCHAR(90) NULL DEFAULT NULL,
  `telefone1` VARCHAR(70) NULL DEFAULT NULL,
  `telefone2` VARCHAR(70) NULL DEFAULT NULL,
  `email1` VARCHAR(90) NULL DEFAULT NULL,
  `email_oficial` VARCHAR(90) NULL DEFAULT NULL,
  `oficio_enviado` VARCHAR(45) NULL DEFAULT NULL,
  `oficio_recebido` VARCHAR(45) NULL DEFAULT NULL,
  `termo_adesao` VARCHAR(45) NULL DEFAULT NULL,
  `link_enviado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_ibge`),
  CONSTRAINT `cod_ibge`
    FOREIGN KEY (`cod_ibge`)
    REFERENCES `form_ipt`.`municipio` (`cod_ibge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
